name: biovectors
channels:
 - conda-forge
dependencies:
 - pip==19.3.1
 - python==3.7.2
 - pip:
   - bayesian-changepoint-detection==0.2.dev1
   - biopython==1.78
   - black==20.8b1
   - flake8==3.8.4
   - gensim==4.1.2
   - jupyter==1.0.0
   - jupyter_client==5.3.4
   - jupyter_console==6.0.0
   - jupyter_core==4.6.0
   - jupytext==1.9.1
   - imageio==2.9.0
   - ipykernel==5.1.2
   - matplotlib==3.3.3
   - numpy==1.17.5
   - pandas==1.1.4
   - plotnine==0.7.1
   - plydata==0.4.3
   - pre_commit==2.9.3
   - ratelimit==2.2.1
   - scikit-learn==0.23.2
   - scipy==1.5.4
   - spacy==2.2.3
   - tqdm==4.35.0
   - umap-learn==0.5.1